### PR TITLE
chore: Add basic CI setup

### PR DESCRIPTION
**Pull request by nschonni**
Add some CI setups to call the linting and schema sync testing to see if the there is a diff after the call.

### CODE REVIEW

**Comment by nschonni** [comment]
I ran into the same lockfile generation as @igetgames, so I added the `--no-package-lock` for the CI

**Review by DavidAnson — CHANGES_REQUESTED** [review]
Nice, thank you! Could you please model this on `ci.yml` from markdownlint? For example, the name, triggers, formatting and so on. In this case, I agree it is not necessary to use an OS or Node matrix or a schedule, but I would like `workflow_dispatch` and any other goodies like `--no-package-lock`.

**Review by DavidAnson — COMMENTED** [review]
Looks good! I'm ready to merge. Can you confirm the diff check after schema fails CI if there are changes?

**Comment by nschonni** [comment]
Added a test commit to show what happens when the schema sync changes something. Here is the failing CI https://github.com/nschonni/vscode-markdownlint/runs/1468216656?check_suite_focus=true#step:7:13
Going to rebase off the commit now though

**Review by DavidAnson — APPROVED** [review]
Perfect, thanks for checking!

**Pull request merged**
