### PR TITLE
chore: Copy testing setup from yo code

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by DavidAnson** [comment]
I like the idea, but I haven't seen a good way to test extension behavior like this. In the beginning, the extension did very little beyond the library, so it didn't matter much. Now, it's more capable, but the challenge of testing remains in my mind. Maybe you know what's possible here and it's enough to be worthwhile?

**Comment by nschonni** [comment]
I was able to see it working locally using the debugger task to launch a separate process. It didn't seem to like running as `npm test` inside VS code, but I was more trying to get it running with CI before digging into the test cases.

**Comment by DavidAnson** [comment]
That seems totally fine – I only use the command line anyway. I guess my big question is what a basic test looks like in this system: create a document, type some Markdown, verify the right errors are raised, verify the options to fix/docs work. Without good integration into VS Code, this seems difficult to do.

**Comment by nschonni** [comment]
Agree that most of the test belong at the library level. Few random thoughts for IDE specific ones:
- Working with a good/bad extension that adds/contributes rules
- Handling of malformed config. I usually see those warnings when you're typing out a config or save too early in VSCode when setting up a new repo
- If an "init/generate" function gets added to create a config file
- Sanity tests for new VSCode versions/oldest supported version for APIs

**Comment by DavidAnson** [comment]
With the release of v0.40 and the use of `markdownlint-cli2` as the engine for the extension, I hope it's even less necessary to validate core functionality than before. There's something to be said for UI-level automation testing of an extension within VS Code, but that seems bigger than what this level of testing allows. I'm closing this PR since I don't think this is the path I'd take. But thanks for taking the time and proposing this!

**Pull request closed without merging**
