### PR TITLE
Fix editor focus loss

### LINKED ISSUE #184: Editor loses focus on edit when a local copy of markdownlint is not installed
👋

I cloned a repo with a local `markdownlint-cli` setup, forgot to run `yarn install` and started editing a markdown. Surprisingly, the editor ended up losing focus each time markdownlint was trying to check the file. This made typing pretty much impossible – here is how it looked:

Kapture 2021-08-14 at 12 46 33

I typed two words. The first one got printed, but the other one got lost because I ended up typing into the output channel.

Looks like the problem is in how [`outputChannel.show()` is called](https://github.com/DavidAnson/vscode-markdownlint/blob/007db6eae1ad4d99597cf5514eb514f438eebf24/extension.js#L102). According to the [method signature](https://github.com/microsoft/vscode/blob/15c86782298a32e175b476673e1511d3ae43ed49/src/vs/vscode.d.ts#L5553-L5558), the problem should be fixeable by passing `true` as the first argument (which is `preserveFocus`). I did this in my local copy of the extension and it worked! The output channel still pops up (which is good), but the cursor remains in the editor.

### PR DESCRIPTION
**Pull request by kachkaev**
Closes #184

### CODE REVIEW

**Comment by DavidAnson** [comment]
Thanks, looks good!

There is a failing check, but it's not your fault - probably a dependency change. I'll resolve that before accepting this PR.

**Review by DavidAnson — CHANGES_REQUESTED** [review]
Please update the PR to be for "next" branch.

**Comment by kachkaev** [comment]
Thanks for looking at the PR @DavidAnson! I’ll try to resolve the issue by the end of this weekend 🙌

**Comment by DavidAnson** [comment]
Just update it to be against `next` branch instead of `main` and it should pass. I think you can do this in the UI.

**Comment by kachkaev** [comment]
I’ve changed the target branch but CI still shows as failing. Happy to make further tweaks if necessary 🙂

**Review by DavidAnson — APPROVED** [review]
I'll accept, I think CI isn't doing the rebase.

**Pull request merged**
