### PR TITLE
chore: Bump js-yaml for npm audit

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by DavidAnson** [comment]
Thanks! I am waiting to do this until I add one more feature to the markdownlint package.

**Comment by nschonni** [comment]
No problem, feel free to replace it with yours, just figured I see if I could figure it out since I ran into the schema issue

**Comment by DavidAnson** [comment]
You got it right! :) If you want to send a separate PR for js-yaml, I can accept that now.

**Comment by nschonni** [comment]
OK, I'll just rebase this one to just include that commit, and you can push the package changes when you're ready.

PS: running NPM install was what caused the re-ordering. I think it wants "-" before "l" when it re-writes the file

**Comment by DavidAnson** [comment]
Great, thanks!

**Pull request merged**
